version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: famflix-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  voice-agent:
    build:
      context: .
      dockerfile: voice_agents/Dockerfile
    image: famflix/voice-agent:latest
    container_name: famflix-voice-agent
    environment:
      # Provide keys via env or an env_file
      ELEVEN_API_KEY: ${ELEVEN_API_KEY:-}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      # Optional CrewAI/OpenAI for agent flow
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      VOICE_AGENT_API_KEY: ${VOICE_AGENT_API_KEY:-}
      # Defaults (tunable)
      STABILITY_DEFAULT: ${STABILITY_DEFAULT:-0.55}
      DIALOGUE_STABILITY_DEFAULT: ${DIALOGUE_STABILITY_DEFAULT:-0.35}
      SIMILARITY_DEFAULT: ${SIMILARITY_DEFAULT:-0.7}
      STYLE_DEFAULT: ${STYLE_DEFAULT:-0.0}
      SPEED_DEFAULT: ${SPEED_DEFAULT:-1.0}
      REDIS_URL: "redis://redis:6379"
    ports:
      - "8001:8001"
    volumes:
      - clone_uploads:/tmp/clone_uploads
    depends_on:
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: voice_agents/Dockerfile
    image: famflix/voice-agent:latest # Use the same image
    container_name: famflix-voice-worker
    command: python -m rq worker --url redis://redis:6379 default
    environment:
      # Worker needs same env vars to access APIs and settings
      ELEVEN_API_KEY: ${ELEVEN_API_KEY:-}
      ELEVENLABS_API_KEY: ${ELEVENLABS_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      VOICE_AGENT_API_KEY: ${VOICE_AGENT_API_KEY:-}
      STABILITY_DEFAULT: ${STABILITY_DEFAULT:-0.55}
      DIALOGUE_STABILITY_DEFAULT: ${DIALOGUE_STABILITY_DEFAULT:-0.35}
      SIMILARITY__DEFAULT: ${SIMILARITY_DEFAULT:-0.7}
      STYLE_DEFAULT: ${STYLE_DEFAULT:-0.0}
      SPEED_DEFAULT: ${SPEED_DEFAULT:-1.0}
      REDIS_URL: "redis://redis:6379"
    volumes:
      - clone_uploads:/tmp/clone_uploads
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  clone_uploads:
