---
policy_and_cost_guard_supervision:
  description: >-
    Perform comprehensive pre-processing checks before allowing synthesis
    to proceed. Execute these validations in order: 1) Confirm consent flag {consent_flag}
    is present for any user-provided voice, 2) Confirm TTS provider is ElevenLabs
    (reject if {provider} != "elevenlabs"), 3) Enforce rate guards including max text
    length per job (text length ≤ {max_text_length}) and daily character cap if applicable
    ({daily_char_limit}). Stop the entire workflow early if any check fails.
  expected_output: >-
    A strict JSON response: {"ok": true, "reason": "checks passed"}
    if all validations succeed, or {"ok": false, "reason": "specific failure reason"}
    if any check fails (e.g., "missing consent", "provider not ElevenLabs", "text
    too long", "daily limit exceeded").
  agent: supervisor

audio_preprocessing_for_elevenlabs:
  description: >-
    Process raw audio file at {raw_audio_path} through the complete audio
    preprocessing pipeline for ElevenLabs TTS/cloning preparation. Execute these steps
    in order: 1) Resample to 16 kHz mono if needed, 2) VAD trim long silences using
    Silero VAD while preserving natural micro-pauses, 3) Apply light denoising without
    over-suppression to avoid metallic artifacts, 4) Loudness normalize to -20 LUFS
    with true peak ≤ -2 dBFS, 5) Perform speaker diarization and keep only the dominant
    speaker by merging their segments in timestamp order, 6) Export final single WAV
    file at 16 kHz mono. Ensure quality standards: no clipping, no music/FX, no other
    speakers, minimized background noise, intelligible speech, and consistent loudness.
    If input is unusable (multi-speaker overlap everywhere, <10s usable speech), return
    clear error with brief reason.
  expected_output: >-
    A JSON object containing the absolute path to the cleaned audio
    file: {"clean_wav_path": "/abs/path/to/cleaned_single_speaker.wav"}. If processing
    fails due to unusable input, return error JSON: {"error": "brief reason why input
    is unusable"}.
  agent: audio_engineer
  context:
  - policy_and_cost_guard_supervision

elevenlabs_tts_generation:
  description: >-
    Generate natural speech from {text} using ElevenLabs TTS with voice
    ID {voice_id}. Use mode {mode} to determine initial settings (dialogue_stability
    for "dialogue" mode, stability for others). Apply defaults from {defaults} object
    for similarity_boost, style, and speed. Follow provider lock: use ElevenLabs API
    only. Split very long text into sentence-sized chunks while preserving tone continuity.
    Cache results if (voice_id, text, settings) combination was previously generated.
    On retry requests, adjust only the requested parameters within acceptable ranges
    while maintaining voice timbre.
  expected_output: >-
    A JSON object containing: {"gen_wav_path": "/abs/path/to/generated.wav",
    "settings_used": {"stability": 0.55, "similarity_boost": 0.7, "style": 0.0, "speed":
    1.0}, "was_cached": false}. Never leak raw API responses, return only the audio
    result path and settings used.
  agent: synthesis_specialist
  context:
  - audio_preprocessing_for_elevenlabs

audio_quality_control_with_auto_retry:
  description: >-
    Evaluate generated audio clip quality by running ASR WER analysis
    and speaker similarity checks. Compare {gen_wav_path} against {text} for intelligibility
    (WER ≤ {max_wer}) and against {ref_voice_wav} for voice fidelity (cosine ≥ {min_cosine}).
    If either check fails and no prior retry exists, request single auto-retry from
    Synthesis Specialist with parameter adjustments: similarity_boost += {cosine_bump_similarity}
    (≤ {similarity_cap}) if cosine low, stability += {cosine_bump_stability} (≤ {stability_cap})
    if delivery unstable. Re-evaluate retry result and make final decision.
  expected_output: >-
    A JSON object with decision, metrics, and details: {"decision":
    "pass", "metrics": {"wer": 0.06, "speaker_cosine": 0.88, "transcript": "the recognized
    text here"}, "final_wav_path": "/abs/path/to/accepted.wav", "retries_used": 0,
    "notes": "short rationale"}
  agent: qc_listener
  context:
  - elevenlabs_tts_generation

